### ISSUE TITLE
Elasticsearch  2.2.0无法使用

### ISSUE THREAD

**Issue by wulikui** [ysc/word#11]
ERROR: Plugin [word] is incompatible with Elasticsearch [2.2.0]. Was designed for version [2.1.1]

**Comment by freemsly** [comment]
good

**Comment by freemsly** [comment]
how to install and use it in windows for Elasticsearch [2.1.1]? where can i find example for it？

**Comment by ysc** [comment]
use plugin.bat instead of plugin.
