### ISSUE TITLE
WordFrequencyStatistics里做分词时为何有时候有词性有的时候没有？？

### ISSUE THREAD

**Issue by kylinzlkz** [ysc/word#13]
例子结果如：
[[明天, 下雨], [结合, 成, 分子], [明天/t, 有/v, 关于/p, 分子/n, 和/c, 原子/n, 的/uj, 课程/n], [下雨, 了, 也要, 去, 听课]]
为什么第三句有词性，其他都没有啊？？ 我不知道在哪设置QWQ 我想全都有词性...

**Comment by ysc** [comment]
之所以会这样，是因为在分词的时候，有的句子标注了词性并使用词性来从多个分词结果中选择一个最好的分词结果，而有的句子并不需要。
如果需要词性，则需要使用如下方法手动指定：
//词性标注
PartOfSpeechTagging.process(words);


在项目主页第11条有说明

**Comment by xiaosan1009** [comment]
请把我的邮箱移除，谢谢

iPhoneから送信

2016/03/10 22:24、杨尚川 <notifications@github.com> のメッセージ:
