### ISSUE TITLE
关于SimHashPlusHammingDistanceTextSimilarity的问题

### ISSUE THREAD

**Issue by kudi1991** [ysc/word#14]
你好，我试用了SimHashPlusHammingDistanceTextSimilarity这个相似度算法，发现毫无相似性的两个文本，计算出来的相似性都在0.8以上。

例如：“医院”和“香港新闻网3月10日电 据香港《商报》报道，昨公布最新人民币环球指数，1月指数较12月上升3.1%至2228点，主要原因是今年初人民币贬值后，离岸人民币汇市成交量大增。表示，指数回升可能只是短暂的现象，而实际趋势仍然疲弱。企业可能因为担心中国政府进一步限制资金外流，而将更多人民币资金保留在境外帐户，终止2015年年中以来离岸人民币存款量下降的趋势。”

**Comment by ysc** [comment]
你这个例子太极端了，你的文本1只有一个词，而文本2却那么长。

还有就是simhash的方式不是很准。
