### ISSUE TITLE
多语言相似度计算

### ISSUE THREAD

**Issue by hanasian** [ysc/word#18]
杨哥下午好！我叫韩亚洲。
看了您写的博客真心学到好多东西， 在此亚洲真心感激！
这里我遇到两个问题，找不到联系你的方式只能在此提问了。
1.多语言监测的问题，给一段文本能准确识别它是哪个国家的语言？
2.准确计算多种语言(中英日韩德西等)相似度的问题，看您写了那么多计算相似度的算法，可是面对多语言，如何准确得出相似度呢？那么多种语言，一定要进行分词吗？
给我点建议吧，这是我的扣扣1534433176.

**Comment by ysc** [comment]
1、你可以用这个项目来检测多语言：[A language detection library for the JVM](https://github.com/melix/jlangdetect)
2、相似度算法跟语言无关，计算两段文本的相似度实质是计算两个词列表的相似度：double scoreImpl(List<Word> words1, List<Word> words2)，不同语言有不同的分词方法，分好词后调用相似度算法即可。
