### ISSUE TITLE
使用V1.2版本在elastaicsearch下分词错误

### ISSUE THREAD

**Issue by tsunli** [ysc/word#2]
1.按照elasticsearch插件安装说明安装
  a. elasticsearch-1.4.4
  b../plugin -u http://apdplat.org/word/archive/v1.2.zip -i word
2.测试分词:http://localhost:9200/paper/_analyze?text=中国人民&analyzer=word
返回:{"tokens": [ ]}
不能正确分词.
3.http://localhost:9200/paper/_analyze?text=中华人民共和国&analyzer=word
结果为:
tokens": [
{"token": "华人民",
"start_offset": 1,
"end_offset": 4,
"type": "word",
"position": 2},
{"token": "共和国",
"start_offset": 4,
"end_offset": 7,
"type": "word",
"position": 3}]

**Comment by ysc** [comment]
返回空不是不能正确分词，而是 中国 人民 这两个词都是停用词，被过滤掉了。

我这里访问：http://localhost:9200/_analyze?text=中华人民共和国&analyzer=word 的时候，返回值是：
{"tokens":[{"token":"中华","start_offset":0,"end_offset":2,"type":"word","position":1},{"token":"共和国","start_offset":4,"end_offset":7,"type":"word","position":3}]}
同理，人民 是停用词，被过滤了。

如果需要自己指定停用词，则将配置文件中的停用词路径指定为你自己的文件路径即可，在配置文件 plugins/word/word.local.conf 中修改配置项：
stopwords.path=classpath:stopwords.txt，将classpath:stopwords.txt修改为你自己的路径
