### ISSUE TITLE
语料如何生成

### ISSUE THREAD

**Issue by henghanan** [ysc/word#20]
hi，
请问下，如果我有行业数据，怎样来生成语料文件，进而生成bigram.txt用来做歧义处理？

**Comment by ysc** [comment]
参考这里：[https://github.com/ysc/word/blob/master/src/main/java/org/apdplat/word/corpus/CorpusTools.java](https://github.com/ysc/word/blob/master/src/main/java/org/apdplat/word/corpus/CorpusTools.java)

**Comment by henghanan** [comment]
hi，
我看过这个类，可能我没表达清楚，我想知道的是corpora.zip包里的文件，是怎样生成的？
