### ISSUE TITLE
Solr6.3.0 采用word1.3分词器 高亮显示异常

### ISSUE THREAD

**Issue by niexiaolong** [ysc/word#26]
我在Solr6.3.0上采用word.1.3.jar作为分词器，相应的配置也都按github上的改了，分词没问题，但是高亮出现了偏差。

只要我的内容中有\r\n字符，高亮就会挪位，我加了一个\r，高亮部分就会整体挪动一位。看了源码，标点符号是有加入\r \n \t这些内容的，但高亮很奇怪的是有\t，是不会有问题的。但有\r或者\n，高亮就会错位。

`"highlighting": {

	"PK_3174064": {
		"pj_title": [
			"今天\t<em>宝宝</em>发烧，我也发烧"
		]
	},
	"PK_5028758": {
		"pj_title": [
			"今天<em>\r宝</em>宝发烧，我也发烧"
		]
	},
	"PK_41364016": {
		"pj_title": [
			"今天<em>\n宝</em>宝发烧，我也发烧"
		]
	}
}`

**Comment by china-richway2** [comment]
可能是空字符（空格、换行、半角标点符号等）直接被忽略的缘故，无法判断词语的准确位置。\r\n本身就是用来分割标点符号的符号，所以会被忽略。
我在考虑在Tokenizer里加一个hack，通过indexOf之类的方式寻找词语的准确位置。但不知道有没有更好的解决方案。

**Comment by niexiaolong** [comment]
目前我这边是属于，搜索出来的预览内容里面，都是一些富文本，肯定是会有\r\n的，所以我这边的处理方式，是打算在导入到solr里面去的时候，就把\r\n去掉，然后再导入，来规避问题。

**Comment by china-richway2** [comment]
问题出在Tokenizer的那个readLine()那一行会吃掉一个\r\n，导致偏移两个字符。
目前我用indexOf成功实现高亮无偏移，但是对于少数编码错误的文本会遇到编码问题，indexOf返回-1（文本中找不到分出来的词）。并且有效率问题，对每个词都需要进行一次indexOf。
过几天我测试完成后发一个pull request。
