### ISSUE TITLE
elasticsearch 插件错误

### ISSUE THREAD

**Issue by tsunli** [ysc/word#3]
1. elasticsearch 1.4.4 插件V1.2 对_all 默认字段查询始终找不到数据指定_all中的具体字段名查询没问题.
    a. http://localhost:9200/paper/search?q=矿石 :查询不到结果.
    b. http://localhost:9200/paper/search?q=主题:矿石     有结果
    c.把下面映射中的indexAnalyzer改成其他分词器如mmseg/ansj 可以得到正确的结果.
2._all 字段定义
 "_all": {
        "enabled": true,
        "indexAnalyzer": "word",
        "searchAnalyzer": "word",
        "term_vector": "no",
        "store": "false",
        "include": [
          "作者",
          "作者单位",
          "标题",
          "关键词",
          "主题",
          "摘要"
        ],
        "exclude": [
          "全文"
        ]
      },

  "properties": {
  "主题": {
          "type": "string",
          "analyzer": "word",
          "_boost": 2,
          "include_in_all": "true"
        },
 }
}

**Comment by ysc** [comment]
文件 elasticsearch-1.*.*/config/elasticsearch.yml 中是否有如下配置：    
index.analysis.analyzer.default.type : "word"
index.analysis.tokenizer.default.type : "word"

**Comment by tsunli** [comment]
在 2015年05月15日 11:08, 杨尚川 写道:
>
> 文件 elasticsearch-1././/config/elasticsearch.yml 中是否有如下配置：
>
> index.analysis.analyzer.default.type : "word"
> index.analysis.tokenizer.default.type : "word"
>

可以确认加上这两条配置项与否结果是一样的.
