### ISSUE TITLE
用main运行WordSegmenter的seg等方法的线程执行完不结束退出虚拟机

### ISSUE THREAD

**Issue by gwenson** [ysc/word#37]
用public static void main(String[] args)主方法运行WordSegmenter.seg("国家主席江泽民发表1998年新年讲话java编程是世界上最好的语言NO。1");
在有。等中文或可能其他的符号时，运行完成了，JVM还没关闭，一直等待

**Comment by gwenson** [comment]
我试了下，word在第一次启动时会非常慢，难道是为了下一次分词的速度？

**Comment by niexiaolong** [comment]
有些数据为了保证分词的高效性，需要将它们放到内存中，初始化需要加载分词数据，慢是正常的。
但每一次分词都慢，就不正常了。

**Comment by gwenson** [comment]
@niexiaolong 不是每一次分词都慢，而是分词执行结束后有：‘。’字符的，该线程会一直等待

**Comment by niexiaolong** [comment]
我回答的是你的第二条

**Comment by gwenson** [comment]
@niexiaolong  >_>

**Comment by ysc** [comment]
在word.conf中禁用自动检测功能，这样，main方法执行完毕JVM就会退出：

#是否启用自动检测功能，如：用户自定义词典、停用词词典
auto.detect=false
