### ISSUE TITLE
我想实现短文本的相似度查询，求杨老师指导。

### ISSUE THREAD

**Issue by umeitime** [ysc/word#39]
我在做一个句子发布的系统，就是收录一些名人名言，但是大家发布的时候，我会去库里面查询有没有人发布过，我要查询一下相似度，然后相似度大于某个比例的，我会告诉用户有人发布过。文字的字数在200字左右，需要建立索引，因为可能要比对很大量的数据，从网上看了很多方案，没有发现比较完美的，求杨老师指导，我应该采取什么方案？感谢O(∩_∩)O

**Comment by ysc** [comment]
我刚好有一个短文本搜索服务的开源项目：[https://github.com/ysc/short-text-search](https://github.com/ysc/short-text-search)，和你的需求很匹配，你研究一下。
