### ISSUE TITLE
我需要用相识度计算两个新闻标题的相识度，我用简单共有词得到的是0.586，用编辑距离得到的是0.862,其他几个的我没有试过，不知道用哪个合适

### ISSUE THREAD

**Issue by lidaoyang** [ysc/word#40]
老师，我需要用相识度计算两个新闻标题的相识度，类似（词1：万达股债双杀市值蒸发666亿全世界都等王思聪发微博，词2：万达股债双杀市值半日蒸发666亿元全世界都在等王思聪发微博）我用简单共有词得到的是0.586，用编辑距离得到的是0.862,其他几个的我没有试过，不知道用哪个合适?很头疼啊！请求帮助分析一下用哪个好？

**Comment by ysc** [comment]
首先，你弄一个测试数据集，标注100对句子，并标上相似度分值，分值可以简单地分为五个档次如0，0.25，0.5，0.75，1。
然后，你用各种算法来计算分值，并比较计算出来的分值跟标注分值之间的差距，把这100个差距分值取绝对值累加起来。
最后，哪一种算法的累加值最小，就说明哪一种算法效果最好。
