### ISSUE TITLE
elasticsearch中分词高亮错误

### ISSUE THREAD

**Issue by crystoy** [ysc/word#5]
您好，我在elasticsearch里用word能获取到正确的分词，但在搜索时使用highlight标出的关键词是完全不相关的结果，比如我搜的是“新媒体”一词，但highlight标出的是标点符号和“点子和”这样的没关系的词。不知是我哪里没配置好还是插件有问题，麻烦帮忙分析下，谢谢。

**Comment by ysc** [comment]
这是因为，在默认配置中，是会移除空白字符和标点符号的，所以会出现你说的高亮错位的情况。

见word.conf配置文件：

    #是否保留空白字符
    keep.whitespace=false
    #是否保留标点符号，标点符号的定义见文件：punctuation.txt
    keep.punctuation=false

解决方法为把如上两个配置项修改为true：

    vim  elasticsearch-2.1.1/plugins/word/word-1.4.jar
    选中word.conf文件并回车
    找到如上两项配置并修改为true
    保存文件并退出（按esc键，输入:wq，回车，输入:wq，回车）
