### ISSUE TITLE
solr5.3.1 高亮标记错误

### ISSUE THREAD

**Issue by junyangren** [ysc/word#6]
示例：
输入关键“手机”，高亮显示的位置不对

"<em>手机</em>怎么使用WiFi上网？ 您可以在中国电信WiFi网络区域内<em>，根</em>据手机说明书<em>将天</em>翼手机的WiFi 或WLAN功能打开

**Comment by ysc** [comment]
这是因为，在默认配置中，是会移除空白字符和标点符号的，所以会出现你说的高亮错位的情况。

见word.conf配置文件：

    #是否保留空白字符
    keep.whitespace=false
    #是否保留标点符号，标点符号的定义见文件：punctuation.txt
    keep.punctuation=false

解决方法为把如上两个配置项修改为true

**Comment by niexiaolong** [comment]
哥们你好，把那2个设为true是不是解决问题了。
我这边遇到一个新的问题，和你这个问题有点类似，那就是，内容中有'\r\n'这样的回车换行符，也会导致高亮错位，并且我把\r\n配到punctuation.txt文件，也没有任何变化。这个你有遇到吗？
